export const shopCategories = [
  { value: "art", label: "Art & Craft Supplies" },
  { value: "automotive", label: "Automotive" },
  { value: "baby", label: "Baby & Kids" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "books", label: "Books & Media" },
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "electronics", label: "Electronics & Technology" },
  { value: "fitness", label: "Fitness & Sports" },
  { value: "food", label: "Food & Beverages" },
  { value: "furniture", label: "Furniture & Home Decor" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "health", label: "Health & Wellness" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "music", label: "Musical Instruments" },
  { value: "office", label: "Office & School Supplies" },
  { value: "pets", label: "Pet Supplies" },
  { value: "shoes", label: "Shoes & Footwear" },
  { value: "tools", label: "Tools & Hardware" },
  { value: "toys", label: "Toys & Games" },
  { value: "travel", label: "Travel & Luggage" },
];
